### ISSUE TITLE
Scalable, keepAspectRatio, centering & responsive slider.

### ISSUE THREAD

**Issue by artfulcat** [webbiesdk/SudoSlider#21]
Hello.
Help, please. I can not understand. I can not.

I need to do:
1) Scalable slider (for example, 80% of the container, the size of which varies with window).
2) Inside, I want to receive images scaled more faces (height or width, preserving the aspect ratio) in the slider and centered vertically in it.
3) The height of the slider I want to point out himself (px or %).

Here is the sketch: http://prntscr.com/5yuzo8

Add later: 
centered vertically - fix it: http://prntscr.com/5ywekb

#slider .slidesContainer .slide {
    overflow: hidden;
    height: 580px;
    padding: 0 100px 0 0;
    line-height: 580px;
}
#slider .slide img,
#slider .slide div {
    vertical-align: middle;
}

But the problem of "scale the any pictures (even static slider) is not solved. See the example:
http://prntscr.com/5ywgs4 & http://prntscr.com/5ywhlu

**Comment by webbiesdk** [comment]
I've look a bit at it, and I think you are setting some CSS that fixes the height, because SudoSlider doesn't normally behave like you've shown in the screenshots. 

So, I'm need to see the page you've implemented so far, before I can help anymore (not just screenshots). 

You can send me a mail if you don't want the url to be public.

**Comment by artfulcat** [comment]
On which mailbox to send files?

**Comment by webbiesdk** [comment]
erik@webbies.dk
