### ISSUE TITLE
Question: Video files in slider

### ISSUE THREAD

**Issue by surfchris** [webbiesdk/SudoSlider#23]
Hi

I see that it is possible to include youtube videos in the slider, but is it also possible to use video files (.avi, .mp4, etc)? If not, are there any plans to add such a feature in the near future?

BTW thanks for making such a great slider!! 

Thanks,
Chris

**Comment by webbiesdk** [comment]
The example with Youtube videos is really just an example that you can put almost anything into a slider. 
That includes putting video files in using the HTML5 video tag and other ways of showing video. 
Just because i don't have an example showcasing something doesn't mean that it isn't possible. 

In you case, start by making the video like you would without a slider, then put it in the slider like the rich content has been put in the slider in this demo: http://webbies.dk/assets/files/SudoSlider/package/demos/rich%20content.html

You can risk some bugs if you use effects other that "slide" (which is the default), but other than that it should work fine.

**Comment by surfchris** [comment]
Great! Thank you!
