### ISSUE TITLE
Images taller than the screen

### ISSUE THREAD

**Issue by kylebellamy** [webbiesdk/SudoSlider#41]
I have responsive set, played with autoHeight and Width on and off but can't seem to get the image to resize to fit on the screen. Can you suggest what I am doing wrong?
http://www.uekman.com/test/andrews.html

**Comment by webbiesdk** [comment]
Is it something like this you are looking for: http://webbies.dk/assets/files/SudoSlider/package/demos/responsive.html ?

**Comment by kylebellamy** [comment]
I have the responsive variable in mine but for some reason it does not seem to be acknowledging it. Could it be I am canceling it out with another variable?

<script type="text/javascript">
		$(document).ready(function(){	
		    var sudoSlider = $("#slider").sudoSlider({ 
				effect: "fade",
				numeric: true,
         		continuous: true,
				prevNext: false,
				insertAfter: false,
				autoWidth: true,
				autoHeight: true,
				responsive: true
		   });
		});
	</script>

**Comment by kylebellamy** [comment]
```<script type="text/javascript">
$(document).ready(function(){	
var sudoSlider = $("#slider").sudoSlider({ 
effect: "fade",
numeric: true,
continuous: true,
prevNext: false,
insertAfter: false,
autoWidth: true,
autoHeight: true,
responsive: true
});
});
</script>```

**Comment by webbiesdk** [comment]
SudoSlider seems to be behaving correctly on your page, but the CSS on the slider, and its parents seems to be constricting it. 

As a start, if you remove the CSS `max-width: 600px;` from `#slider`, then the images can get bigger (up to 750px when im testing it.). 

That 750px limit is because the column is at most 750px wide, expanding that allows the images to grow larger. 

Essentially, when responsive is on, SudoSlider grows to fit any container it is put in, but it wont grow larger than the container it is put in. So if you want SudoSlider to fit the screen, you should make the container you put the slider in fit the screen.

**Comment by kylebellamy** [comment]
I took the source from the responsive demo and put in my images showing only one at a time. When the viewer switched to a much taller image, the text on the page was pushed off the bottom by the height of the image. 

I think I misunderstood that the slider was responsive item but the images inside it would remain the size they are. Tall images would not be resized to be fully visible. 

http://uekman.com/test/andrewstest.html

**Comment by webbiesdk** [comment]
I know its been a long time (holiday on my part), but I cannot progress when the examples you link to gives a 404.
