### ISSUE TITLE
Identify current slide

### ISSUE THREAD

**Issue by lebleu29** [webbiesdk/SudoSlider#50]
I'm using custom links as a kind of navigation menu which is working great, but I'm wondering how I would go about indicating to the user in the navigation which slide is currently being displayed.

Ie - in your demos, the background color of the tabs change when you go from slide to slide. 

Thanks.

**Comment by webbiesdk** [comment]
Well, if you are using customLinks, then the class `current` will be added to the customLink that points to the current slide (if you are using data-target="1", or some other number). 

Otherwise, you could use the callbacks: http://webbies.dk/assets/files/SudoSlider/package/demos/basic%20callbacks.html to do something fancy yourself.

**Comment by lebleu29** [comment]
Great, that's what I needed to know. Thanks!

**Comment by webbiesdk** [comment]
Glad to help.
