### ISSUE TITLE
Bug in the demo Thumbnails 2

### ISSUE THREAD

**Issue by Kennersky** [webbiesdk/SudoSlider#53]
This demo will see three thumbnail images when it init with only one ajax image. Like bellow:
`var ajaximages = [
			    '../images/01.jpg'
	        ];`
![1](https://cloud.githubusercontent.com/assets/2129521/15062162/f4d17ebe-136f-11e6-97b8-a7e449b76ff9.jpg)
How to fix that?

**Comment by webbiesdk** [comment]
It is by design. 
In that particular demo i wanted to have the thumbnails "wrap around". (And at the time that i designed it, that effect couldn't be achieved easily with SudoSlider). 
So that if one animated from slide 1 to 3, then the thumbnails would animate nicely, even when there are 4 visible thumbnails and 5 total thumbnails. 

The demos are mostly meant to demonstrate what is possible, so this isn't a bug in SudoSlider, it a "design flaw" in one of the demonstrations of the slider.

**Comment by Kennersky** [comment]
But that thumbnail couldn't stay the right current active when it initialized. like below:
![2](https://cloud.githubusercontent.com/assets/2129521/15089285/9d3f7dea-1432-11e6-95eb-3ca3f609b1be.jpg)
The  perfect status is activing the first thumbnail,but it is not.
